version: '3.7'
services:
    mariadb:
        image: mariadb
        container_name: "mariadb"
        ports:
            - "3306:3306"
        volumes:
            - "./db/mariadb:/var/lib/mysql:rw"
            - "./etc/mysql/:/etc/mysql/"
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
            - "MYSQL_USER=root"
            - "SET GLOBAL sql_mode =''"
        networks:
            - docker_webstack
    web.nginx:
        image: nginx:latest
        container_name: "web.nginx"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./projects/:/var/www/projects"
        depends_on:
            - php7.fpm
            - php5.fpm
            - mariadb
        networks:
            - docker_webstack
    php7.fpm:
        build: php-stack-7-fpm
        container_name: "php7.fpm"
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./projects/:/var/www/projects"
        networks:
            - docker_webstack
    php5.fpm:
        build: php-stack-5.6.30-fpm
        container_name: "php5.fpm"
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./projects/:/var/www/projects"
        networks:
            - docker_webstack
networks:
    docker_webstack:
        driver: bridge